SurfaceContourPoints



SurfaceContourPoints


Returns the vertices of the polyline curves generated by contouring a surface or polysurface object.


Syntax


Rhino.SurfaceContourPoints (strObject, arrStartPoint, arrEndPoint [, dblInterval [, dblAngle]])


Parameters



strObject 

Required.  String.  The identifier of a surface or polysurface object.

arrStartPoint 

Required.  Array.  The 3-D starting point of a center line.

arrEndPoint 

Required.  Array.  The 3-D ending point of a center line.

dblInterval 

Optional.  Number.  The distance between contour curves.  If omitted, the interval will be equal to the diagonal distance of the object's bounding box divided by 50.

dblAngle 

Optional.  Number.  The maximum angle in degrees between unit tangents at adjacent vertices.  If omitted, the maximum angle will be set to 5.0 degrees.


Returns



Array 

An array of 3-D point arrays, one for each contour, if successful.

Null 

If not successful, or on error.


Example


Const rhObjectSurface = 8

Const rhObjectPolysurface = 16

Dim strObject, arrStartPoint, arrEndPoint, arrContours, arrPoints

strObject = Rhino.GetObject("Select object", rhObjectSurface + rhObjectPolysurface)

arrStartPoint = Rhino.GetPoint("Base point of center line")

arrEndPoint = Rhino.GetPoint("Endpoint of center line", arrStartPoint)

arrContours = Rhino.SurfaceContourPoints(strObject, arrStartPoint, arrEndPoint)

If IsArray(arrContours) Then

  For Each arrPoints In arrContours

    Rhino.AddPointCloud arrPoints

  Next

End If


Also See



AddSrfContourCrvs


CurveContourPoints

MeshContourPoints

