SurfaceCylinder



SurfaceCylinder


Returns the definition of a cylinder surface.


Syntax


Rhino.SurfaceCylinder (strSurface)


Parameters



strSurface 

Required.  String.  The surface object's identifier.


Returns



Array 

An array containing the definition of the cylinder if successful.  The elements of the array are as follows:


Element 

Type 

Description

0 

Array 

The base plane of the cylinder.

1 

Number 

The height of the cylinder.

2 

Number 

The radius of the cylinder.


Null 

If not successful, or on error.


Example


Dim strCylinder, arrCylinder

strCylinder = Rhino.AddCylinder(Rhino.WorldXYPlane, 6, 2, False)

If Rhino.IsCylinder(strCylinder) Then

  arrCylinder = Rhino.SurfaceCylinder(strCylinder)

  Rhino.AddCylinder arrCylinder(0), arrCylinder(1), arrCylinder(2), False

End If


Example


SurfaceCone

SurfaceSphere

SurfaceTorus

