[MeshVolumeCentroid]

    Calculates the volume centroid of a mesh object.

[Syntax]

    Rhino.MeshVolumeCentroid (strObject)

[Parameters]

    strObject
    Required.  String.  The identifier of a mesh object.

[Returns]

    Array
    A 3-D point identifying the volume centroid if successful.
    Null
    If not successful, or on error.

[Example]

    Const rhObjectMesh = 32
    Dim strObject
    strObject = Rhino.GetObject("Select mesh", rhObjectMesh )
    Rhino.AddPoint Rhino.MeshVolumeCentroid(strObject)

[Also See]

    IsMesh
    MeshArea
    MeshAreaCentroid
    MeshVolume
