[GetPoint]

    Pauses for user input of a point.

[Syntax]

    Rhino.GetPoint ([strMessage [, arrPoint [, dblDistance [, blnPlane]]]])

[Parameters]

    strMessage
    Optional.  String.  A prompt or message.
    arrPoint
    Optional.  Array.  A zero-based, one-dimensional array containing three numbers identifying a starting, or base, point.
    dblDistance
    Optional.  Number.  A constraining distance.  If a constraining distance is specified, a base point must also be specified.
    blnPlane
    Optional.  Boolean.  Constrain the point selection to the active construction plane.

[Returns]

    Array
    A zero-based, one-dimensional array containing three numbers identifying the 3-D point input by the user successful.
    Null
    If not successful, or on error.

[Example]

    Dim arrPt1, arrPt2, arrPt3, dblDistance
    arrPt1 = Rhino.GetPoint("Pick first point")
    If IsArray(arrPt1) Then
    Rhino.AddPoint(arrPt1)
    arrPt2 = Rhino.GetPoint("Pick second point", arrPt1)
    If IsArray(arrPt2) Then
    Rhino.AddPoint(arrPt2)
    dblDistance = Rhino.Distance(arrPt1, arrPt2)
    arrPt3 = Rhino.GetPoint("Pick third point", arrPt2, dblDistance)
    If IsArray(arrPt3) then
    Rhino.AddPoint arrPt3
    End If
    End If
    End If

[Also See]

    GetPointOnCurve
    GetPointOnSurface
    GetPoints
    GetRectangle
