[RealBox]

    Displays a dialog box prompting the user to enter a number.

[Syntax]

    Rhino.RealBox ([strMessage [, dblNumber [, strTitle]]])

[Parameters]

    strMessage
    Optional.  String.  A prompt or message.
    dblNumber
    Optional.  Number.  A default number..
    strTitle
    Optional.  String.  A dialog box title.

[Returns]

    Number
    The number if successful.
    Null
    If not successful, or on error.

[Example]

    Dim dblRadius, arrPoint
    dblRadius = Rhino.RealBox ("Enter a radius value", 5.0 )
    If Not IsNull(dblRadius) and (dblRadius > 0) Then
    arrPoint = Array(0,0,0)
    Rhino.AddCircle arrPoint, dblRadius
    End If

[Also See]

    GetReal
