PullPoints



PullPoints


Pulls an array of points to a surface or mesh object. For more information, see the Rhino help file for information on the Pull command.


Syntax


Rhino.PullPoints (strObject, arrPoints)


Parameters



strObject 

Required.  String.  The identifier of the surface or mesh object that pulls.

arrPoints 

Required.  String.  An array of 3-D points to pull.


Returns



Array 

An array of 3-D points if successful.

Null 

If not successful, or on error.


Example


Sub TestPullPoints

  Dim arrObjects, strSurface

  strSurface = Rhino.GetObject("Select surface that pulls", 8)

  arrObjects = Rhino.GetObjects("Select points to pull", 1)

 

  Dim nBound, arrPoints

  nBound = UBound(arrObjects)

  ReDim arrPoints( nBound )



  Dim i 

  For i = 0 To nBound

    arrPoints(i) = Rhino.PointCoordinates( arrObjects(i) )

  Next

 

  Dim arrResults

  arrResults = Rhino.PullPoints( strSurface, arrPoints )

  Rhino.AddPoints arrResults

 

End Sub


Also See


PullCurve

