GetPointOnCurve



GetPointOnCurve


Pauses for user input of a point constrained to a curve object.


Syntax


Rhino.GetPointOnCurve (strObject [, strMessage])


Parameters



strObject 

Required.  String.  The object's identifier.

strMessage 

Optional.  String.  A prompt or message.


Returns



Array 

The 3-D point selected by the user if successful.

Null 

If not successful, or on error.


Example


Dim strObject, arrPoint

strObject = Rhino.GetObject("Pick a curve")

If Rhino.IsCurve(strObject) Then

arrPoint = Rhino.GetPointOnCurve(strObject, "Point on curve")

If IsArray(arrPoint) Then

Rhino.AddPoint arrPoint

End If

End If


Also See


GetPoint

GetPointOnMesh

GetPointOnSurface

GetPoints



