SurfaceEditPoints



SurfaceEditPoints


Returns the edit, or Greville, points of a surface object.  For each surface control point, there is a corresponding edit point.


Syntax


Rhino.SurfaceEditPoints (strObject [, blnReturnParameters [, blnReturnAll]])


Parameters



strObject 

Required.  String.  The object's identifier.

blnReturnParameters 

Optional.  Boolean.  If False (default), edit points are returned as an array of 3-D points. If True, edit points are returned as an array U,V surface parameters.

blnReturnAll 

Optional.  Boolean.  If True (default) all surface edit points are returned. If False, the function will returned surface edit points based on whether or not the surface is closed or periodic.


Returns



Array 

If blnReturnParameters is omitted or False, then an array of 3-D edit points if successful.

Array 

If blnReturnParameters is True, then an array of U,V parameter values if successful.

Null 

If not successful, or on error.


Example


Dim strObject, arrPoints

strObject = Rhino.GetObject("Select a surface")

If Rhino.IsSurface(strObject) Then

arrPoints = Rhino.SurfaceEditPoints(strObject)

If IsArray(arrPoints) Then

Rhino.AddPointCloud arrPoints

End If

End If


Also See


IsSurface

SurfacePointCount

SurfacePoints



