PointArrayTransform



PointArrayTransform


Transforms an array of 3-D points.


Syntax


Rhino.PointArrayTransform (arrPoints, arrXform)


Parameters



arrPoints 

Required.  Array.  An array of 3-D points to transform.

arrXform 

Required.  Array.  A valid 4x4 transformation matrix.


Returns



Array 

The resulting array of 3-D points if successful.

Null 

On error.


Example


Dim strObject, arrPoints, arrXform

strObject = Rhino.GetObject("Select object")

arrPoints = Rhino.BoundingBox(strObject)

arrXform = Rhino.XformRotation(45.0, Array(0,0,1), Array(0,0,0))

arrPoints = Rhino.PointArrayTransform(arrPoints, arrXform)

Rhino.AddPoints arrPoints


Also See


PointArrayBoundingBox

PointArrayClosestPoint

