EllipseQuadPoints



EllipseQuadPoints


Returns the quadrant points of an elliptical-shaped curve object.


Syntax


Rhino.EllipseQuadPoints (strObject)


Parameters



strObject 

Required.  String.  The object's identifier.


Returns



Array 

An array of 3-D points identifying the quadrants of the ellipse if successful.

Null 

If not successful, or on error.


Example


Dim strObject

strObject = Rhino.GetObject("Select ellipse")

If Rhino.IsEllipse(strObject) Then

Rhino.AddPoints Rhino.EllipseQuadPoint(strObject)

End If


Also See


IsEllipse

EllipseCenterPoint

