[AddPolyline]

    Adds a polyline curve object to the current model.

[Syntax]

    Rhino.AddPolyline (arrPoints)

[Parameters]

    arrPoints
    Required.  Array.   An array of 3-D points.  Duplicate, consecutive points found in the array will be removed.  The array must contain at least two 3-D points.  If the array contains less than four points, then the first point and the last point must be different.

[Returns]

    String
    The identifier of the new object if successful.
    Null
    If not successful, or on error.

[Example]

    Dim arrPoints
    arrPoints = Rhino.GetPoints(True)
    If IsArray(arrPoints) Then
    Rhino.AddPolyline arrPoints
    End If

[Also See]

    IsPolyline
    PolylineVertices
