[SurfaceCone]

    Returns the definition of a cone surface.

[Syntax]

    Rhino.SurfaceCone (strSurface)

[Parameters]

    strSurface
    Required.  String.  The surface object's identifier.

[Returns]

    Array
    An array containing the definition of the cone if successful.  The elements of the array are as follows:
    Element
    Type
    Description
    0
    Array
    The plane of the cone.  The apex of cone is at plane's origin and  the axis of the cone is plane's z-axis.
    1
    Number
    The height of the cone.
    2
    Number
    The radius of the cone.
    Null
    If not successful, or on error.

[Example]

    Dim strCone, arrCone
    strCone = Rhino.AddCone(Rhino.WorldXYPlane, 6, 2, False)
    If Rhino.IsCone(strCone) Then
    arrCone = Rhino.SurfaceCone(strCone)
    Rhino.AddCone arrCone(0), arrCone(1), arrCone(2), False
    End If

[Example]

[SurfaceCone]

    SurfaceCylinder
    SurfaceSphere
    SurfaceTorus
