AddSrfSectionCrvs



AddSrfSectionCrvs


Adds planar curves resulting from the intersection of a defined cutting plane through a surface or a polysurface. For more information, see the Rhino help file for details on the Section command.


Syntax


Rhino.AddSrfSectionCrvs (strObject, arrPlane)


Parameters



strObject 

Required.  String.  The identifier of a surface or polysurface object.

arrPlane 

Required.  Array.  A plane that defines the cutting plane.


Returns



Array 

An array of strings identifying the newly created section curves if successful.

Null 

If not successful, or on error.


Example


Const rhObjectSurface = 8

Const rhObjectPolysurface = 16

Dim strObject, arrCPlane, arrPlane, arrRPlane

strObject = Rhino.GetObject("Select object", rhObjectSurface + rhObjectPolysurface)

arrCPlane = Rhino.ViewCPlane

arrPlane = Rhino.PlaneFromNormal(arrCPlane(0), arrCPlane(1))

arrRPlane = Rhino.RotatePlane(arrPlane, -45.0, arrPlane(1))

Rhino.AddSrfSectionCrvs strObject, arrRPlane


Also See


AddSrfContourCrvs

