[Str2PtArray]

    Converts a formatted string value into an array of 3-D point value.

[Syntax]

    Rhino.Str2PtArray (strPoints)

[Parameters]

    strPoints
    Required.  String.  A string that contains an unknown number of space delimited points like "1,2,3 4,5,6 7,8,9".

[Returns]

    Array
    An array of 3-D points if successful.
    Null
    If not successful, or on error.

[Example]

    Dim arrPoints
    arrPoints = Rhino.Str2PtArray("1,2,3 4,5,6 7,8,9")
    If IsArray(arrPoints) Then
    Rhino.AddPointCloud arrPoints
    End If

[Also See]

    Pt2Str
    Str2Pt
