LinePlane



LinePlane


Returns a plane that contains the line.  The origin of the plane is at the start of the line.  If possible, a plane parallel to the world XY, YZ or ZX plane is returned.


Syntax


Rhino.LinePlane (arrLine)


Parameters



arrLine 

Required.  Array.  Two 3-D points identifying the starting and ending points of the line.


Returns



Array 

The plane if successful.  The elements of a plane array are as follows:


Element 

Description

0 

The plane's origin (3-D point).

1 

The plane's X axis direction (3-D vector).

2 

The plane's Y axis direction (3-D vector).

3 

The plane's Z axis direction (3-D vector).


Null 

If not successful, or on error.


Example


Dim arrFrom, arrTo, arrPlane, dblDistance

arrFrom = Array(0, 0, 0)

arrTo = Array(10, 10, 0)

dblDistance = Rhino.Distance(arrFrom, arrTo)

arrPlane = Rhino.LinePlane(Array(arrFrom, arrTo))

Rhino.AddPlaneSurface arrPlane, dblDistance, dblDistance


Also See


LineClosestPoint

LineIsFartherThan

LineMaxDistanceTo

LineMinDistanceTo

LineTransform



