ObjectHasMesh



ObjectHasMesh


Verifies that an object has custom render mesh parameters.


Syntax


Rhino.ObjectHasMesh (strObject)


Parameters



strObject 

Required.  Object.  The identifier of a meshable object.


Returns



Boolean 

True of the object has custom render mesh parameters, False otherwise.

Null 

On error.


Example


Dim strObject

strObject = Rhino.GetObject("Select object")

If Rhino.ObjectHasMesh(strObject) = False Then

Rhino.AddObjectMesh strObject, 1, True

End If


Also See


AddObjectMesh

EnableObjectMesh

ObjectMeshDensity

ObjectMeshMaxAngle

ObjectMeshMaxAspectRatio

ObjectMeshMaxDistEdgeToSrf

ObjectMeshMaxEdgeLength

ObjectMeshMinEdgeLength

ObjectMeshMinInitialGridQuads

ObjectMeshQuality

ObjectMeshSettings

