[AddNamedCPlane]

    Adds a new named construction plane to the document.

[Syntax]

    Rhino.AddNamedCPlane (strName [, strView])

[Parameters]

    strName
    Required.  String.  The name of the new named construction plane.
    strView
    Optional.  String.  The title or identifier of the view from which to save the construction plane.  If omitted, the current active view is used.

[Returns]


[Parameters]

    String
    The name of the newly created named construction plane if successful.
    Null
    If not successful, or on error.

[Example]

    Dim arrViews, strView, strName
    arrViews = Rhino.ViewNames
    If IsArray(arrViews) Then
    For Each strView In arrViews
    strName = strView & "_cplane"
    Rhino.AddNamedCPlane strName, strView
    Next
    End If

[Also See]

    DeleteNamedCPlane
    NamedCPlane
    NamedCPlanes
    RestoreNamedCPlane
