AddInterpCrvOnSrf



AddInterpCrvOnSrf


Adds an interpolated curve object that lies on a specified surface. Note, this function will not create periodic curves, but it will create closed curves.


Syntax


Rhino.AddInterpCrvOnSrf (strObject, arrPoints)


Parameters



strObject 

Required.  String.  The surface object's identifier.

arrPoints 

Required.  Array.  An array of 3-D points that lie on the specified surface. The array must contain at least two points.


Returns



String 

The identifier of the new object if successful.

Null 

If not successful, or on error.


Example


Const rhObjectSurface = 8

Dim strObject, arrPt1, arrPt2

strObject = Rhino.GetObject("Select surface to draw curve on", rhObjectSurface)

If VarType(strObject) = vbString Then

arrPt1 = Rhino.GetPointOnSurface(strObject, "First point on surface")

If IsArray(arrPt1) Then

arrPt2 = Rhino.GetPointOnSurface(strObject, "Second point on surface")

If IsArray(arrPt2) Then

Rhino.AddInterpCrvOnSrf strObject, Array(arrPt1, arrPt2)

End If

End If

End If


Also See


AddCurve

AddInterpCurve

AddInterpCrvOnSrfUV



