CurveFrame



CurveFrame


Returns the plane at a parameter of a curve. The plane is based on the tangent and curvature vectors at a parameter.


Syntax


Rhino.CurveFrame (strObject, dblParameter)


Parameters



strObject 

Required.  String.  The object's identifier.

dblParameter 

Required.  Number. The parameter to evaluate.


Returns



Array 

The plane at the specified parameter if successful.

Null 

If not successful, or on error.


Example


Dim arrCurve, arrPlane

arrCurve = Rhino.GetCurveObject("Select a curve")

If IsArray(arrCurve) Then

arrPlane = Rhino.CurveFrame(arrCurve(0), arrCurve(4))

Rhino.AddPlaneSurface arrPlane, 5.0, 3.0)

End If


Also See


CurvePerpFrame

