CurveDiscontinuity



CurveDiscontinuity


Search for a derivatitive, tangent, or curvature discontinuity in a curve object.


Syntax


Rhino.CurveDiscontinuity (strObject [, intType])


Parameters



strObject 

Required.  String.  The object's identifier.

intStyle 

Required.  Number.  The type of continuity to test for.  The types of continuity are as follows:


Value 

Description

1 

C0 - Continuous function

2 

C1 - Continuous first derivative

3 

C2 - Continuous first and second derivative

4 

G1 - Continuous unit tangent

5 

G2 - Continuous unit tangent and curvature



Returns



Array 

An array of 3-D points where the curve is discontinuous if successful.

Null 

If not successful, or on error.


Example


Dim strObject, arrPoints

strObject = Rhino.GetObject("Select a curve", 4)

If Rhino.IsCurve(strObject) Then

  arrPoints = Rhino.CurveDiscontinuity(strObject, 2)

  If IsArray(arrPoints) Then

    Rhino.AddPoints arrPoints

  End If

End If


Also See


IsCurve

