DivideCurve



DivideCurve


Divides a curve object into a specified number of segments.


Syntax


Rhino.DivideCurve (strObject, lngSegments [, blnCreate [, blnPoints]])


Parameters



strObject 

Required. String. The object's identifier.

lngSegments 

Required. Number. The number of segments.

blnCreate 

Optional. Boolean. Create the division points. If omitted or False, points are not created.

blnPoints 

Optional. Boolean. Return an array of 3-D points. If omitted or True, points are returned. If False, then an array of curve parameters are returned.


Returns



Array 

If blnPoints is not specified or True, then an array containing 3-D division points if successful.

Array 

If blnPoints is False, then an array containing division curve parameters if successful.

Null 

If not successful, or on error.


Example


Dim strObject, arrPoints, arrPoint

strObject = Rhino.GetObject("Select a curve")

If Rhino.IsCurve(strObject) Then

arrPoints = Rhino.DivideCurve(strObject, 4)

For Each arrPoint In arrPoints

Rhino.AddPoint arrPoint

Next

End If


Also See


DivideCurveEquidistant

DivideCurveLength



