ViewNearCorners



ViewNearCorners


Returns the 3-D corners points of a view's near clipping plane rectangle. This function can be useful in determining the "real world" size of a parallel-projected view.


Syntax


Rhino.ViewNearCorners ([strView])


Parameters



strView 

Optional.  String.  The title or identifier of the view.  If omitted, the current active view is used.


Returns



Array 

An array of four 3-D points that define the corners of the rectangle if successful.  Points are returned in counter-clockwise order.

Null 

If not successful, or on error.


Example


Dim arrRect

arrRect = Rhino.ViewNearCorners

If IsArray(arrRect) Then

  Rhino.AddTextDot "0", arrRect(0)

  Rhino.AddTextDot "1", arrRect(1)

  Rhino.AddTextDot "2", arrRect(2)

  Rhino.AddTextDot "3", arrRect(3)

End If


Also See


CurrentView

