AddCone



AddCone


Adds a cone-shaped polysurface to the document.


Syntax


Rhino.AddCone (arrBase, arrHeightPnt, dblRadius [, blnCap])

Rhino.AddCone (arrPlane, dblHeight, dblRadius [, blnCap]))


Parameters



arrBase 

Required.  Array.  The 3-D origin point of the cone.

arrPlane 

Required.  Array.  The cone's base plane.  The apex of cone is at plane's origin and  the axis of the cone is plane's z-axis.

arrHeightPnt 

Required.  Array.  The 3-D height point of the cone.  The height point defines the height and direction of the cone.

dblHeight 

Required.  Number.  The height of the cone.  If arrPlane is specified, then the center of the arrPlane is height * the plane's z-axis.

dblRadius 

Required.  Number.  The radius at the base of the cone.  Note, tan(cone_angle) = dblRadius/ dblHeight.

blnCap 

Optional.  Boolean.  Cap the base of the cone.  The default is to cap the cone (True).


Returns



String 

The identifier of the new object if successful.

Null 

If not successful, or on error.


Example


Dim arrBase, arrHeightPnt, dblRadius

dblRadius = 5.0

arrBase = Rhino.GetPoint("Base of cone")

If IsArray(arrBase) Then

arrHeightPnt = Rhino.GetPoint("Height of cone", arrBase)

If IsArray(arrHeightPnt) Then

Rhino.AddCone arrBase, arrHeightPnt, dblRadius

End If

End If


Also See


AddBox

AddCylinder

AddSphere

AddTorus

