AddCircle3Pt



AddCircle3Pt


Adds a 3-point circle curve to the document.


Syntax


Rhino.AddCircle3Pt (arrFirst, arrSecond, arrThird)


Parameters



arrStart 

Required.  Array. The first point of the circle.

arrEnd 

Required.  Array.  The second point of the circle.

arrPoint 

Required.  Array.  The third point of the circle.


Returns



String 

The identifier of the new object if successful.

Null 

If not successful, or on error.


Example


Dim arrFirst, arrSecond, arrThird

arrFirst = Rhino.GetPoint("First point on circle")

If IsArray(arrFirst) Then

arrSecond = Rhino.GetPoint("Second point on circle")

If IsArray(arrSecond) Then

arrThird = Rhino.GetPoint("Third point on circle")

If IsArray(arrThird) Then

Rhino.AddCircle3Pt arrFirst, arrSecond, arrThird

End If

End If

End If


Also See


AddCircle

CircleCenterPoint

CircleCircumference

CircleRadius

IsCircle



