AddInterpCurveEx



AddInterpCurveEx


Adds an interpolated curve object to  the document similar to Rhino's InterpCrv command.


Syntax


Rhino.AddInterpCurveEx (arrPoints [, intDegree [, intKnotStyle [, blnSharp [, arrStartTangent [, arrEndTangent]]]]])


Parameters



arrPoints 

Required.  Array.  An array containing 3-D points to interpolate. Note, the number of control points must be >= (intDegree+1).

intDegree 

Optional.  Number.  The degree of the curve.  If omitted, degree = 3 is used.  The degree of the curve must be >=1.  Periodic curves must have a degree >= 2.  For intKnotStyle = 1 or 2, the degree must be 3.

intKnotStyle 

Optional.  Number. The knot style to use. If omitted, a knot style = 0 is used. The knot style determines how an interpolated curve will be parameterized.


Value 

Description

0 

Uniform.  The knot spacing is always 1 and is not based on the physical spacing of points.

1 

Chord. The spacing between the points is used for the knot spacing

2 

Square Root Chord. The square root of the spacing between points is used for the knot spacing.


blnSharp 

Optional.  Boolean.  If True, when you create a closed curve, it will have a kink at the start/end point. If False (default), a smooth closure will be created.

arrStartTangent 

Optional.  Array.  A 3-D vector that specifies a tangency condition at the beginning of the curve.

arrEndTangent 

Optional.  Array.  A 3-D vector that specifies a tangency condition at the end of the curve.


Returns



String 

The identifier of the new object if successful.

Null 

If not successful, or on error.


Example


Dim arrPoints

arrPoints = Rhino.GetPoints(True, , "Pick curve point")

If IsArray(arrPoints) Then

Rhino.AddInterpCurveEx arrPoints

End If


Also See


AddCurve

AddInterpCurve

CurvePointCount

IsCurve

