EllipseCenterPoint



EllipseCenterPoint


Returns the center point of an elliptical-shaped curve object.


Syntax


Rhino.EllipseCenterPoint (strObject)


Parameters



strObject 

Required.  String.  The object's identifier.


Returns



Array 

The 3-D center point of the ellipse if successful.

Null 

If not successful, or on error.


Example


Dim strObject, arrPoint

strObject = Rhino.GetObject("Select ellipse")

If Rhino.IsEllipse(strObject) Then

arrPoint = Rhino.EllipseCenterPoint(strObject)

Rhino.AddPoint arrPoint

End If


Also See


IsEllipse

EllipseQuadPoints



