AddCylinder



AddCylinder


Adds a cylinder-shaped polysurface to the document.


Syntax


Rhino.AddCylinder (arrBase, arrHeightPnt, dblRadius [, blnCap])

Rhino.AddCylinder (arrPlane, dblHeight, dblRadius [, blnCap])


Parameters



arrBase 

Required.  Array.  The 3-D base point of the cylinder.

arrPlane 

Required.  Array.  The base plane of the cylinder.

arrHeightPnt 

Required.  Array.  The 3-D height point of the cylinder.  The height point defines the height and direction of the cylinder.

dblHeight 

Required.  Number.  The height of the cylinder.

dblRadius 

Required.  Number.  The radius of the cylinder.

blnCap 

Optional.  Boolean.  Cap the ends of the cylinder.  If omitted, the ends of the cylinder will be capped (True).


Returns



String 

The identifier of the new object if successful.

Null 

If not successful, or on error.


Example


Dim arrBase, arrHeightPnt, dblRadius

dblRadius = 5.0

arrBase = Rhino.GetPoint("Base of cylinder")

If IsArray(arrBase) Then

arrHeightPnt = Rhino.GetPoint("Height of cylinder", arrBase)

If IsArray(arrHeightPnt) Then

Rhino.AddCylinder arrBase, arrHeightPnt, dblRadius

End If

End If


Also See


AddBox

AddCone

AddSphere

AddTorus

