[RectangularLightPlane]

    Returns the plane of a rectangular light object.

[Syntax]

    Rhino.RectangularLightPlane (strObject)

[Parameters]

    strObject
    Required.  String.  The light object's identifier.

[Returns]

    Array
    The plane if successful.  The elements of a plane array are as follows:
    Element
    Type
    Description
    0
    Array
    The plane's origin (3-D point).
    1
    Array
    The plane's X axis direction (3-D vector).
    2
    Array
    The plane's Y axis direction (3-D vector).
    3
    Array
    The plane's Z axis direction (3-D vector).
    
    Note, the X axis, Y axis, and Z axis have magnitude that  indicate the extents of the rectangular light.
    Null
    If not successful, or on error.

[Example]

    Const rhObjectLight = 256
    Dim strObject, arrPlane, dblLength, dblWidth
    strObject = rhino.GetObject("Select a rectangular light",  rhObjectLight)
    If Rhino.IsRectangularLight(strObject) Then
    arrPlane = Rhino.RectangularLightPlane(strObject)
    If IsArray(arrPlane) Then
    dblLength = Rhino.VectorLength( arrPlane(1) )
    dblWidth = Rhino.VectorLength( arrPlane(2) )
    Rhino.AddPlaneSurface arrPlane, dblLength, dblWidth
    End If
    End If

[Also See]

    IsRectangularLight
