AddNamedView



AddNamedView


Adds a new named view to the document.


Syntax


Rhino.AddNamedView (strName [, strView])


Parameters



strName 

Required.  String.  The name of the new named view.

strView 

Optional.  String.  The title or identifier of the view to save.  If omitted, the current active view is saved.


Returns



String 

The name of the newly created named view if successful.

Null 

If not successful, or on error.


Example


Dim arrViews, strView, strName

arrViews = Rhino.ViewNames

If IsArray(arrViews) Then

For Each strView In arrViews

strName = strView & "_view"

Rhino.AddNamedView strName, strView

Next

End If


Also See


DeleteNamedView

NamedViews

RestoreNamedView

