[AddBox]

    Adds a new box-shaped polysurface to the document.

[Syntax]

    Rhino.AddBox (arrCorners)

[Parameters]

    arrCorners
    Required.  Array.  An array of eight 3-D points that define the corners of the box.  Points need to be  in counter-clockwise order starting with the bottom rectangle of the box.

[Returns]

    String
    The identifier of the new object if successful.
    Null
    If not successful, or on error.

[Example]

    Dim arrBox
    arrBox = Rhino.GetBox
    If IsArray(arrBox) Then
    Rhino.AddBox arrBox
    End If

[Also See]

    AddCone
    AddCylinder
    AddSphere
    AddTorus
