[AddPlanarSrf]

    Creates one or more surfaces from planar curves.

[Syntax]

    Rhino.AddPlanarSrf (arrObjects)

[Parameters]

    arrObjects
    Required.  Array.  An array of curve object identifiers.

[Returns]

    Array
    An array of strings identifying the new objects if successful.
    Null
    If not successful, or on error.

[Example]

    Const rhObjectCurve = 4
    Dim arrObjects
    arrObjects = Rhino.GetObjects("Select planar curves to build surface", rhObjectCurve)
    If IsArray(arrObjects) Then
    Rhino.AddPlanarSrf arrObjects
    End If

[Also See]

    AddEdgeSrf
    AddSrfControlPtGrid
    AddSrfPt
    AddSrfPtGrid
