[AddSrfPtGrid]

    Creates a surface from a grid of points.

[Syntax]

    Rhino.AddSrfPtGrid (arrCount, arrPoints [, arrDegree [, arrClosed]])

[Parameters]

    arrCount
    Required.  Array.  The number of points in the U and V directions.
    arrPoints
    Required.  Array.  An array of 3-D points.
    arrDegree
    Optional.  Array.  The degree of the surface in the U and V directions.  If omitted, the degree of the new surface in the U and V directions will be 3.
    arrClosed
    Optional.  Array.  Whether or not the surface is closed in the U and V directions.  If omitted, the new surface will not be closed in either the U or V directions.

[Returns]

    String
    The identifier of the new object if successful.
    Null
    If not successful, or on error.

[Example]

    Dim arrCount(1), arrPoints(24), nCount, i, j
    arrCount(0) = 5
    arrCount(1) = 5
    nCount = 0
    For i = 0 to arrCount(0) - 1
    For j = 0 to arrCount(1) - 1
    arrPoints(nCount) = Array(i*2, j*4, 0)
    nCount = nCount + 1
    Next
    Next
    Rhino.AddSrfPtGrid arrCount, arrPoints

[Also See]

    AddEdgeSrf
    AddSrfControlPtGrid
    AddSrfPt
