[AddClippingPlane]

    Creates a clipping plane. A clipping plane is a plane for visibly clipping away geometry in a specific view. Note, clipping planes are infinite.

[Syntax]

    Rhino.AddClippingPlane (arrPlane, dblDU, dblDV, [strView])
    Rhino.AddClippingPlane (arrPlane, dblDU, dblDV, [arrViews])

[Parameters]

    arrPlane
    Required.  Array.  The plane.
    dblDU
    Required.  Number.  The magnitude in the U direction.
    dblDV
    Required.  Number.  The magnitude in the V direction.
    strView
    Optional.  String.  The title of the view to clip.  If omitted, the current active view is used.
    arrViews
    Optional.  Array.  The titles of the views to clip.  If omitted, the current active view is used.

[Returns]

    String
    The identifier of the new object if successful.
    Null
    If not successful, or on error.

[Example]

    Rhino.AddClippingPlane Rhino.WorldXYPlane, 5.0, 3.0

[Also See]

    IsClippingPlane
